#!/bin/bash
osascript <<EOD
tell application "Finder"
activate

set theAction to button returned of (display dialog "

You are not the assigned user of this computer.
Admin privileges are not available.

If you need assistance, please contact support.

" buttons {"OK"} default button 1 giving up after 45 with title "Error Not Allowed" with icon Stop)

end tell
EOD
exit 0
